<a href="https://colab.research.google.com/github/raunakdwivedi03/Python_Libraries/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
## creating numpy
import numpy as np

a=np.array([1,2,3])
print(type(a))
print(a)


<class 'numpy.ndarray'>
[1 2 3]


In [6]:
#2d or #3D #called matrix
b=np.array([[1,2,3,4],[4,5,3,2]])
print(b)

[[1 2 3 4]
 [4 5 3 2]]


In [5]:
# tensor
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [12]:
#dtype
a=np.array([1,2,3],dtype=float)
print(a)
b=np.array([1,2,3],dtype=bool)
print(b)
c=np.array([1,2,3],dtype=complex)
print(c)
d=np.array([1,2,3],dtype=int)
print(d)


[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]
[1 2 3]


In [15]:
#np.a range
a=np.arange(1,11)
print(a)
b=np.arange(1,11,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [23]:
##reshape  --> given numpy array ko cahnge kr detea hai
a=np.arange(1,13).reshape(2,6)  #syntax -> .reshape(rows, col)
print(a)
b=np.arange(1,11).reshape(5,2)
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [26]:
##np.ones and np.zeros
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
##random number
np.random.random((3,2))

array([[0.60901905, 0.1082853 ],
       [0.51200447, 0.61908336],
       [0.5583897 , 0.87143208]])

In [32]:
##np.linear space or linspace
np.linspace(-10,10,5)

array([-10.,  -5.,   0.,   5.,  10.])

In [33]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#ARRAY attribute

In [51]:
a1=np.arange(11,dtype=np.int32)
a2=np.arange(12,dtype=float).reshape(3,4)
print(a2)
a3=np.arange(8).reshape(2,2,2)
print(a3)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [40]:
##ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)


1
2
3


In [45]:
#shape --> btata  hai ki kitne number of items exist krte hai
a1.shape
print(a1)
print(a2.shape)

[ 0  1  2  3  4  5  6  7  8  9 10]
(3, 4)


In [48]:
#size --> number fo items kitne honge
print(a1.size)
print(a2.size)
print(a3.size)

11
12
8


In [52]:
##itemsize
a1.itemsize  ##byte btata hai

4

In [53]:
a3.itemsize

8

In [54]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


#Changing Datatype

In [55]:
#astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)