<a href="https://colab.research.google.com/github/raunakdwivedi03/Python_Libraries/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## creating numpy
import numpy as np

a=np.array([1,2,3])
print(type(a))
print(a)


<class 'numpy.ndarray'>
[1 2 3]


In [2]:
#2d or #3D #called matrix
b=np.array([[1,2,3,4],[4,5,3,2]])
print(b)

[[1 2 3 4]
 [4 5 3 2]]


In [3]:
# tensor
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [4]:
#dtype
a=np.array([1,2,3],dtype=float)
print(a)
b=np.array([1,2,3],dtype=bool)
print(b)
c=np.array([1,2,3],dtype=complex)
print(c)
d=np.array([1,2,3],dtype=int)
print(d)


[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]
[1 2 3]


In [5]:
#np.a range
a=np.arange(1,11)
print(a)
b=np.arange(1,11,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [6]:
##reshape  --> given numpy array ko cahnge kr detea hai
a=np.arange(1,13).reshape(2,6)  #syntax -> .reshape(rows, col)
print(a)
b=np.arange(1,11).reshape(5,2)
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [7]:
##np.ones and np.zeros
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
##random number
np.random.random((3,2))

array([[0.94116572, 0.20262701],
       [0.30034901, 0.63383666],
       [0.90514482, 0.17410421]])

In [10]:
##np.linear space or linspace
np.linspace(-10,10,5)

array([-10.,  -5.,   0.,   5.,  10.])

In [11]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#ARRAY attribute

In [12]:
a1=np.arange(11,dtype=np.int32)
a2=np.arange(12,dtype=float).reshape(3,4)
print(a2)
a3=np.arange(8).reshape(2,2,2)
print(a3)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [13]:
##ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)


1
2
3


In [14]:
#shape --> btata  hai ki kitne number of items exist krte hai
a1.shape
print(a1)
print(a2.shape)

[ 0  1  2  3  4  5  6  7  8  9 10]
(3, 4)


In [15]:
#size --> number fo items kitne honge
print(a1.size)
print(a2.size)
print(a3.size)

11
12
8


In [16]:
##itemsize
a1.itemsize  ##byte btata hai

4

In [17]:
a3.itemsize

8

In [18]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


#Changing Datatype

In [19]:
#astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

#Array Opn.

In [23]:
a1=np.arange(0,12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [25]:
##scaler operations

#airthemetic
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [33]:
#realtional
print(a2==5)

print(a2==12)
 ## jha pe eqaul hoga vo true ho jaega
print(a2>=12)

print(a2>25)

print(a2!=12)

[[False False False False]
 [False False False False]
 [False False False False]]
[[ True False False False]
 [False False False False]
 [False False False False]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [False False False False]
 [False False False False]]
[[False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [41]:
##vector operations --> when we have apply the opn on to numpy arrrays

##airthmetic operations

print(a1+a2)


print(a2-a1)

print((a1-a2))


print(a1*a2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]


#Array functions

In [45]:
a1=np.random.random((3,3))
print(a1)
a1=np.round(a1*100)
print(a1)

[[0.97158564 0.78565744 0.74923026]
 [0.91338098 0.71323987 0.3290535 ]
 [0.43002177 0.42038416 0.99112475]]
[[97. 79. 75.]
 [91. 71. 33.]
 [43. 42. 99.]]


In [53]:
#max/min/sum/prod
#0--> col  and 1--> row
print(np.max(a1))
print(np.min(a1,axis=1))
print(np.prod(a1,axis=0))
print(np.sum(a1))
print(np.sum(a1,axis=0))


99.0
[75. 33. 42.]
[379561. 235578. 245025.]
630.0
[231. 192. 207.]


In [56]:
##median/mean/std/var --> statistical operations
print(np.median(a1))
print(np.mean(a1))
print(np.std(a1))
print(np.var(a1))

print(np.median(a2))
print(np.mean(a2))
print(np.std(a2))
print(np.var(a2))

print(np.median(a2,axis=0))
print(np.mean(a2,axis=0))
print(np.std(a2,axis=0))
print(np.var(a2,axis=0))

75.0
70.0
23.570226039551585
555.5555555555555
17.5
17.5
3.452052529534663
11.916666666666666
[16. 17. 18. 19.]
[16. 17. 18. 19.]
[3.26598632 3.26598632 3.26598632 3.26598632]
[10.66666667 10.66666667 10.66666667 10.66666667]


In [61]:
##trignometric operations
print(np.sin(a1))

print(np.cos(a1))

print(np.tan(a1))

[[ 0.37960774 -0.44411267 -0.38778164]
 [ 0.10598751  0.95105465  0.99991186]
 [-0.83177474 -0.91652155 -0.99920683]]
[[-0.92514754 -0.89597095  0.92175127]
 [-0.99436746 -0.30902273 -0.01327675]
 [ 0.5551133  -0.39998531  0.03982088]]
[[ -0.4103213    0.49567753  -0.42070095]
 [ -0.10658787  -3.0776204  -75.3130148 ]
 [ -1.49838734   2.29138799 -25.09253498]]


In [63]:
##dot product --> if (3,4) and (4,3) if in this ordered pair the i==j then it is call the dot product and the resultant is (3,3)
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
np.dot(a2,a3)


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [64]:
##log and exponent
print(np.log(a1))
print(np.exp(a1))

[[4.57471098 4.36944785 4.31748811]
 [4.51085951 4.26267988 3.49650756]
 [3.76120012 3.73766962 4.59511985]]
[[1.33833472e+42 2.03828107e+34 3.73324200e+32]
 [3.31740010e+39 6.83767123e+30 2.14643580e+14]
 [4.72783947e+18 1.73927494e+18 9.88903032e+42]]


In [76]:
##round / floor / and ciel
print(np.random.random((2,3))*100)
print(np.round(np.random.random((2,3))*100)) ## o/p round off krke dega


[[38.86569653 89.91337767 85.62044989]
 [90.57894607 43.54667816 80.98030554]]
[[21. 73. 63.]
 [59.  1. 13.]]


In [74]:
np.floor(np.random.random((2,3))*100) ## floor peeche vaale numbers ko deta hai

array([[60., 72., 73.],
       [ 0., 13., 17.]])

In [75]:
np.ceil(np.random.random((2,3))*100) ## nearest aage vale ko deta hai

array([[71., 34., 24.],
       [98., 67., 34.]])

#Indexing and Slicing

In [82]:
a1=np.random.random((3,3))
print(a1)
a2=np.arange(12).reshape(3,4)
print(a2)
a3=np.arange(8).reshape(2,2,2)
print(a3)


[[0.64011279 0.66720092 0.25670758]
 [0.43152165 0.25694595 0.43601928]
 [0.40539097 0.57200086 0.68848541]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [83]:
a1[-1]#indexing

array([0.40539097, 0.57200086, 0.68848541])

In [84]:
a1[0]

array([0.64011279, 0.66720092, 0.25670758])

In [85]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
a2[1,2]  # a[row, col]

np.int64(6)

In [87]:
a2[1,0]

np.int64(4)

In [88]:
#3D tensor --> 2D se banta hai
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [89]:
#find 5
a3[1,0,1]


np.int64(5)

In [90]:
a3[0,0,0]

np.int64(0)

In [91]:
a3[0,1,1] #a[2d vala matrix, then  row , col]

np.int64(3)

In [92]:
a3[1,1,0]

np.int64(6)

#slicing

ek sath multiple items nikal skte hai


In [93]:
a1

array([[0.64011279, 0.66720092, 0.25670758],
       [0.43152165, 0.25694595, 0.43601928],
       [0.40539097, 0.57200086, 0.68848541]])

In [94]:
a1[2:5]

array([[0.40539097, 0.57200086, 0.68848541]])

In [95]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

socho konse col chahie or konse rows chahie

In [103]:
a2[1,::3,]

array([4, 7])

In [101]:
a2[::2,1::2,]

array([[ 1,  3],
       [ 9, 11]])

In [96]:
a2[0,:] #a[row, konsa col ]

array([0, 1, 2, 3])

In [97]:
a2[:,2]

array([ 2,  6, 10])

In [98]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [99]:
a2[::2,::3,]

array([[ 0,  3],
       [ 8, 11]])

In [106]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [116]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [109]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [110]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [111]:
a3[::3]

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [112]:
a3[0,1,:]

array([3, 4, 5])

In [113]:
a3[1,1,:]

array([12, 13, 14])

In [114]:
a3[1,:,1]

array([10, 13, 16])

In [115]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

#Iterating

In [125]:
a1=np.array([1,2,3,4,5,6,7,8,9,10,11])
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [126]:
for i in a1:
    print(i)

1
2
3
4
5
6
7
8
9
10
11


In [127]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [129]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [128]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [130]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [131]:
for i in np.nditer(a3): ## pehle 1d me change krega then find kr skte hai
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


#Reshaping

In [ ]:
##reshape


In [132]:
##transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [133]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [134]:
##ravel
a3.ravel() ## 2D ko 1D me change kr deta hai

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

#Stacking

do numpy array ko ya horizonatlly ya verticall stack kr skte hai

In [136]:
##horizontal stacking --> shaping me dimesion same hona chahie
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [137]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [140]:
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [139]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#Spliting

In [141]:
##horizontal spliting
a4=np.arange(16).reshape(4,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [143]:
np.hsplit(a4,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
#vertical spliting

In [147]:
np.vsplit(a4,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]